### ISSUE TITLE
Error when attempting to connect to chatroom

### ISSUE THREAD

**Issue by EvanHope** [allison-liem/unity-twitch#1]
When attempting to connect to the chat room I get the following error: SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

System.Net.Sockets.Socket.Receive (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) (at <6bb7fefcaacb438db8964dbe54b13572>:0)
System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 size) (at <6bb7fefcaacb438db8964dbe54b13572>:0)
Rethrow as IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Twitch Application Settings:
OAuth Redirect URLs: https://id.twitch.tv/oauth2/authorize
Client Type: Public

Unity Settings:
Initialize on Start: True
Username: <twitch user name>
Access Code: <access code from URL>
Chatroom: <twitch user name>

Please let me know if you need any more details.

**Comment by allison-liem** [comment]
Was the username, access code and chatroom filled in?

**Comment by EvanHope** [comment]
Yes, please see the screen shot below.
![Screenshot 2024-03-20 091442](https://github.com/allison-liem/unity-twitch/assets/78510271/5b51e5fb-60c6-474e-a7fb-1e6bd4beb65b)

Thankyou for the quick response.

**Comment by EvanHope** [comment]
Seems to be an issue with my network firewall settings. Attempting it on a different network was successful.
